"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first 
ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their 
difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
difference are pentagonal and D = |Pk − Pj| is minimised; what is the 
value of D?
"""

def pent(n):
	return(((3 * (n ** 2)) - n) // 2)

pentagonals = []

for i in range(1,1000):
	pentagonals.append(pent(i))

for i in range(len(pentagonals)):
	for j in range(i, len(pentagonals)):
		if (pentagonals[i] - pentagonals[j] in pentagonals) and (pentagonals[i] + pentagonals[j] in pentagonals):
			print(pentagonals[i], pentagonals[j])
